set_property SRC_FILE_INFO {cfile:E:/mandelbrot/scalp_user_design/scalp_user_design.srcs/constrs_1/imports/files/scalp_firmware.xdc rfile:../../../scalp_user_design.srcs/constrs_1/imports/files/scalp_firmware.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:E:/mandelbrot/scalp_user_design/scalp_user_design.srcs/constrs_1/imports/files/timing_constraints.xdc rfile:../../../scalp_user_design.srcs/constrs_1/imports/files/timing_constraints.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA19 [get_ports UsbVbusPwrFaultxSI]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G8 [get_ports Pll2V5ClkuWirexCO]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G7 [get_ports Pll2V5DatauWirexSO]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G6 [get_ports Pll2V5LEuWirexSO]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F6 [get_ports Pll2V5GOExSO]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H6 [get_ports Pll2V5LDxSI]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H5 [get_ports Pll2V5SyncxSO]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J3 [get_ports Pll2V5ClkIn0LOSxSI]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K2 [get_ports Pll2V5ClkIn1LOSxSI]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K8 [get_ports HdmiTXCecxSIO]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L7 [get_ports HdmiTXHpdxSI]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N8 [get_ports {HdmiTXPxDO[2]}]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P8 [get_ports {HdmiTXNxDO[2]}]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M8 [get_ports {HdmiTXPxDO[1]}]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M7 [get_ports {HdmiTXNxDO[1]}]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L6 [get_ports {HdmiTXPxDO[0]}]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M6 [get_ports {HdmiTXNxDO[0]}]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J7 [get_ports HdmiTXClkPxSO]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J6 [get_ports HdmiTXClkNxSO]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L4 [get_ports {SwitchesxDI[0]}]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T1 [get_ports {SwitchesxDI[1]}]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K4 [get_ports {JoystickxDI[0]}]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P7 [get_ports {JoystickxDI[1]}]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R7 [get_ports {JoystickxDI[2]}]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J2 [get_ports {JoystickxDI[3]}]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J1 [get_ports {JoystickxDI[4]}]
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J5 [get_ports IoExtIICSdaxDIO]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K5 [get_ports IoExtIICSclxDIO]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L2 [get_ports Led12V5RxSO]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L1 [get_ports Led12V5GxSO]
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R8 [get_ports Led12V5BxSO]
set_property src_info {type:XDC file:1 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T16 [get_ports Led22V5RxSO]
set_property src_info {type:XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports Led22V5GxSO]
set_property src_info {type:XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA20 [get_ports Led22V5BxSO]
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H8 [get_ports SelfRstxRNO]
set_property src_info {type:XDC file:1 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_operating_conditions -grade extended -process maximum
set_property src_info {type:XDC file:1 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_operating_conditions -airflow 0 -heatsink none -board small
set_property src_info {type:XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[4]}]
set_property src_info {type:XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[7]}]
set_property src_info {type:XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[11]}]
set_property src_info {type:XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[12]}]
set_property src_info {type:XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[14]}]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[3]}]
set_property src_info {type:XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[5]}]
set_property src_info {type:XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[2]}]
set_property src_info {type:XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[9]}]
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[15]}]
set_property src_info {type:XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[0]}]
set_property src_info {type:XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[1]}]
set_property src_info {type:XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[13]}]
set_property src_info {type:XDC file:2 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[16]}]
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[18]}]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[19]}]
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[6]}]
set_property src_info {type:XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[8]}]
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[17]}]
set_property src_info {type:XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[10]}]
set_property src_info {type:XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[1]}]
set_property src_info {type:XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[2]}]
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[3]}]
set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[9]}]
set_property src_info {type:XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[15]}]
set_property src_info {type:XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[10]}]
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[12]}]
set_property src_info {type:XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[16]}]
set_property src_info {type:XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[19]}]
set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[0]}]
set_property src_info {type:XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[4]}]
set_property src_info {type:XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[5]}]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[8]}]
set_property src_info {type:XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[14]}]
set_property src_info {type:XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[6]}]
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[7]}]
set_property src_info {type:XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[11]}]
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[13]}]
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[17]}]
set_property src_info {type:XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[18]}]
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/dina[0]}]
set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/dina[1]}]
set_property src_info {type:XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/dina[2]}]
set_property src_info {type:XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/dina[3]}]
set_property src_info {type:XDC file:2 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/doutb[0]}]
set_property src_info {type:XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/doutb[1]}]
set_property src_info {type:XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/doutb[2]}]
set_property src_info {type:XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/doutb[3]}]
set_property src_info {type:XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {PLxB.ImGenxB.interations_s[0]} {PLxB.ImGenxB.interations_s[1]} {PLxB.ImGenxB.interations_s[2]} {PLxB.ImGenxB.interations_s[3]} {PLxB.ImGenxB.interations_s[4]} {PLxB.ImGenxB.interations_s[5]} {PLxB.ImGenxB.interations_s[6]}]]
set_property src_info {type:XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {PLxB.ImGenxB.mandel_addr_s[0]} {PLxB.ImGenxB.mandel_addr_s[1]} {PLxB.ImGenxB.mandel_addr_s[2]} {PLxB.ImGenxB.mandel_addr_s[3]} {PLxB.ImGenxB.mandel_addr_s[4]} {PLxB.ImGenxB.mandel_addr_s[5]} {PLxB.ImGenxB.mandel_addr_s[6]} {PLxB.ImGenxB.mandel_addr_s[7]} {PLxB.ImGenxB.mandel_addr_s[8]} {PLxB.ImGenxB.mandel_addr_s[9]} {PLxB.ImGenxB.mandel_addr_s[10]} {PLxB.ImGenxB.mandel_addr_s[11]} {PLxB.ImGenxB.mandel_addr_s[12]} {PLxB.ImGenxB.mandel_addr_s[13]} {PLxB.ImGenxB.mandel_addr_s[14]} {PLxB.ImGenxB.mandel_addr_s[15]} {PLxB.ImGenxB.mandel_addr_s[16]} {PLxB.ImGenxB.mandel_addr_s[17]} {PLxB.ImGenxB.mandel_addr_s[18]} {PLxB.ImGenxB.mandel_addr_s[19]}]]
set_property src_info {type:XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets Clk125xC]
