set_property SRC_FILE_INFO {cfile:E:/mandelbrot/scalp_user_design/scalp_user_design.srcs/constrs_1/imports/files/scalp_firmware.xdc rfile:../../../scalp_user_design.srcs/constrs_1/imports/files/scalp_firmware.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:E:/mandelbrot/scalp_user_design/scalp_user_design.srcs/constrs_1/imports/files/timing_constraints.xdc rfile:../../../scalp_user_design.srcs/constrs_1/imports/files/timing_constraints.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA19 [get_ports UsbVbusPwrFaultxSI]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G8 [get_ports Pll2V5ClkuWirexCO]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G7 [get_ports Pll2V5DatauWirexSO]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G6 [get_ports Pll2V5LEuWirexSO]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F6 [get_ports Pll2V5GOExSO]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H6 [get_ports Pll2V5LDxSI]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H5 [get_ports Pll2V5SyncxSO]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J3 [get_ports Pll2V5ClkIn0LOSxSI]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K2 [get_ports Pll2V5ClkIn1LOSxSI]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K8 [get_ports HdmiTXCecxSIO]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L7 [get_ports HdmiTXHpdxSI]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N8 [get_ports {HdmiTXPxDO[2]}]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P8 [get_ports {HdmiTXNxDO[2]}]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M8 [get_ports {HdmiTXPxDO[1]}]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M7 [get_ports {HdmiTXNxDO[1]}]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L6 [get_ports {HdmiTXPxDO[0]}]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M6 [get_ports {HdmiTXNxDO[0]}]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J7 [get_ports HdmiTXClkPxSO]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J6 [get_ports HdmiTXClkNxSO]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L4 [get_ports {SwitchesxDI[0]}]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T1 [get_ports {SwitchesxDI[1]}]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K4 [get_ports {JoystickxDI[0]}]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P7 [get_ports {JoystickxDI[1]}]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R7 [get_ports {JoystickxDI[2]}]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J2 [get_ports {JoystickxDI[3]}]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J1 [get_ports {JoystickxDI[4]}]
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J5 [get_ports IoExtIICSdaxDIO]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K5 [get_ports IoExtIICSclxDIO]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L2 [get_ports Led12V5RxSO]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L1 [get_ports Led12V5GxSO]
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R8 [get_ports Led12V5BxSO]
set_property src_info {type:XDC file:1 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T16 [get_ports Led22V5RxSO]
set_property src_info {type:XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports Led22V5GxSO]
set_property src_info {type:XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA20 [get_ports Led22V5BxSO]
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H8 [get_ports SelfRstxRNO]
set_property src_info {type:XDC file:1 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_operating_conditions -grade extended -process maximum
set_property src_info {type:XDC file:1 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_operating_conditions -airflow 0 -heatsink none -board small
set_property src_info {type:XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[4]}]
set_property src_info {type:XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[7]}]
set_property src_info {type:XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[11]}]
set_property src_info {type:XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[12]}]
set_property src_info {type:XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[14]}]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[3]}]
set_property src_info {type:XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[5]}]
set_property src_info {type:XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[2]}]
set_property src_info {type:XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[9]}]
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[15]}]
set_property src_info {type:XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[0]}]
set_property src_info {type:XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[1]}]
set_property src_info {type:XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[13]}]
set_property src_info {type:XDC file:2 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[16]}]
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[18]}]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[19]}]
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[6]}]
set_property src_info {type:XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[8]}]
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[17]}]
set_property src_info {type:XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addra[10]}]
set_property src_info {type:XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[1]}]
set_property src_info {type:XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[2]}]
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[3]}]
set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[9]}]
set_property src_info {type:XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[15]}]
set_property src_info {type:XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[10]}]
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[12]}]
set_property src_info {type:XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[16]}]
set_property src_info {type:XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[19]}]
set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[0]}]
set_property src_info {type:XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[4]}]
set_property src_info {type:XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[5]}]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[8]}]
set_property src_info {type:XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[14]}]
set_property src_info {type:XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[6]}]
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[7]}]
set_property src_info {type:XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[11]}]
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[13]}]
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[17]}]
set_property src_info {type:XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/addrb[18]}]
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/dina[0]}]
set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/dina[1]}]
set_property src_info {type:XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/dina[2]}]
set_property src_info {type:XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/dina[3]}]
set_property src_info {type:XDC file:2 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/doutb[0]}]
set_property src_info {type:XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/doutb[1]}]
set_property src_info {type:XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/doutb[2]}]
set_property src_info {type:XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {PLxB.ImGenxB.video_mem_inst/doutb[3]}]
set_property src_info {type:XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {PLxB.ImGenxB.interations_s[0]} {PLxB.ImGenxB.interations_s[1]} {PLxB.ImGenxB.interations_s[2]} {PLxB.ImGenxB.interations_s[3]} {PLxB.ImGenxB.interations_s[4]} {PLxB.ImGenxB.interations_s[5]} {PLxB.ImGenxB.interations_s[6]}]]
set_property src_info {type:XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {PLxB.ImGenxB.mandel_addr_s[0]} {PLxB.ImGenxB.mandel_addr_s[1]} {PLxB.ImGenxB.mandel_addr_s[2]} {PLxB.ImGenxB.mandel_addr_s[3]} {PLxB.ImGenxB.mandel_addr_s[4]} {PLxB.ImGenxB.mandel_addr_s[5]} {PLxB.ImGenxB.mandel_addr_s[6]} {PLxB.ImGenxB.mandel_addr_s[7]} {PLxB.ImGenxB.mandel_addr_s[8]} {PLxB.ImGenxB.mandel_addr_s[9]} {PLxB.ImGenxB.mandel_addr_s[10]} {PLxB.ImGenxB.mandel_addr_s[11]} {PLxB.ImGenxB.mandel_addr_s[12]} {PLxB.ImGenxB.mandel_addr_s[13]} {PLxB.ImGenxB.mandel_addr_s[14]} {PLxB.ImGenxB.mandel_addr_s[15]} {PLxB.ImGenxB.mandel_addr_s[16]} {PLxB.ImGenxB.mandel_addr_s[17]} {PLxB.ImGenxB.mandel_addr_s[18]} {PLxB.ImGenxB.mandel_addr_s[19]}]]
set_property src_info {type:XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {PLxB.ImGenxB.hdmi_addr_s[0]} {PLxB.ImGenxB.hdmi_addr_s[1]} {PLxB.ImGenxB.hdmi_addr_s[2]} {PLxB.ImGenxB.hdmi_addr_s[3]} {PLxB.ImGenxB.hdmi_addr_s[4]} {PLxB.ImGenxB.hdmi_addr_s[5]} {PLxB.ImGenxB.hdmi_addr_s[6]} {PLxB.ImGenxB.hdmi_addr_s[7]} {PLxB.ImGenxB.hdmi_addr_s[8]} {PLxB.ImGenxB.hdmi_addr_s[9]} {PLxB.ImGenxB.hdmi_addr_s[10]} {PLxB.ImGenxB.hdmi_addr_s[11]} {PLxB.ImGenxB.hdmi_addr_s[12]} {PLxB.ImGenxB.hdmi_addr_s[13]} {PLxB.ImGenxB.hdmi_addr_s[14]} {PLxB.ImGenxB.hdmi_addr_s[15]} {PLxB.ImGenxB.hdmi_addr_s[16]} {PLxB.ImGenxB.hdmi_addr_s[17]} {PLxB.ImGenxB.hdmi_addr_s[18]} {PLxB.ImGenxB.hdmi_addr_s[19]}]]
set_property src_info {type:XDC file:2 line:99 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {PLxB.ImGenxB.y_msb[0]} {PLxB.ImGenxB.y_msb[1]} {PLxB.ImGenxB.y_msb[2]} {PLxB.ImGenxB.y_msb[3]} {PLxB.ImGenxB.y_msb[4]} {PLxB.ImGenxB.y_msb[5]} {PLxB.ImGenxB.y_msb[6]} {PLxB.ImGenxB.y_msb[7]} {PLxB.ImGenxB.y_msb[8]} {PLxB.ImGenxB.y_msb[9]} {PLxB.ImGenxB.y_msb[10]} {PLxB.ImGenxB.y_msb[11]} {PLxB.ImGenxB.y_msb[12]} {PLxB.ImGenxB.y_msb[13]} {PLxB.ImGenxB.y_msb[14]} {PLxB.ImGenxB.y_msb[15]} {PLxB.ImGenxB.y_msb[16]} {PLxB.ImGenxB.y_msb[17]} {PLxB.ImGenxB.y_msb[18]} {PLxB.ImGenxB.y_msb[19]} {PLxB.ImGenxB.y_msb[20]} {PLxB.ImGenxB.y_msb[21]} {PLxB.ImGenxB.y_msb[22]} {PLxB.ImGenxB.y_msb[23]} {PLxB.ImGenxB.y_msb[24]} {PLxB.ImGenxB.y_msb[25]} {PLxB.ImGenxB.y_msb[26]} {PLxB.ImGenxB.y_msb[27]} {PLxB.ImGenxB.y_msb[28]} {PLxB.ImGenxB.y_msb[29]} {PLxB.ImGenxB.y_msb[30]} {PLxB.ImGenxB.y_msb[31]}]]
set_property src_info {type:XDC file:2 line:102 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {PLxB.ImGenxB.imag_00_generate_s[1][0]} {PLxB.ImGenxB.imag_00_generate_s[1][1]} {PLxB.ImGenxB.imag_00_generate_s[1][2]} {PLxB.ImGenxB.imag_00_generate_s[1][3]} {PLxB.ImGenxB.imag_00_generate_s[1][4]} {PLxB.ImGenxB.imag_00_generate_s[1][5]} {PLxB.ImGenxB.imag_00_generate_s[1][6]} {PLxB.ImGenxB.imag_00_generate_s[1][7]} {PLxB.ImGenxB.imag_00_generate_s[1][8]} {PLxB.ImGenxB.imag_00_generate_s[1][9]} {PLxB.ImGenxB.imag_00_generate_s[1][10]} {PLxB.ImGenxB.imag_00_generate_s[1][11]} {PLxB.ImGenxB.imag_00_generate_s[1][12]} {PLxB.ImGenxB.imag_00_generate_s[1][13]} {PLxB.ImGenxB.imag_00_generate_s[1][14]} {PLxB.ImGenxB.imag_00_generate_s[1][15]} {PLxB.ImGenxB.imag_00_generate_s[1][16]} {PLxB.ImGenxB.imag_00_generate_s[1][17]}]]
set_property src_info {type:XDC file:2 line:105 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {PLxB.ImGenxB.imag_00_generate_s[4][0]} {PLxB.ImGenxB.imag_00_generate_s[4][1]} {PLxB.ImGenxB.imag_00_generate_s[4][2]} {PLxB.ImGenxB.imag_00_generate_s[4][3]} {PLxB.ImGenxB.imag_00_generate_s[4][4]} {PLxB.ImGenxB.imag_00_generate_s[4][5]} {PLxB.ImGenxB.imag_00_generate_s[4][6]} {PLxB.ImGenxB.imag_00_generate_s[4][7]} {PLxB.ImGenxB.imag_00_generate_s[4][8]} {PLxB.ImGenxB.imag_00_generate_s[4][9]} {PLxB.ImGenxB.imag_00_generate_s[4][10]} {PLxB.ImGenxB.imag_00_generate_s[4][11]} {PLxB.ImGenxB.imag_00_generate_s[4][12]} {PLxB.ImGenxB.imag_00_generate_s[4][13]} {PLxB.ImGenxB.imag_00_generate_s[4][14]} {PLxB.ImGenxB.imag_00_generate_s[4][15]} {PLxB.ImGenxB.imag_00_generate_s[4][16]} {PLxB.ImGenxB.imag_00_generate_s[4][17]}]]
set_property src_info {type:XDC file:2 line:106 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {PLxB.ImGenxB.imag_00_generate_s[6][0]} {PLxB.ImGenxB.imag_00_generate_s[6][1]} {PLxB.ImGenxB.imag_00_generate_s[6][2]} {PLxB.ImGenxB.imag_00_generate_s[6][3]} {PLxB.ImGenxB.imag_00_generate_s[6][4]} {PLxB.ImGenxB.imag_00_generate_s[6][5]} {PLxB.ImGenxB.imag_00_generate_s[6][6]} {PLxB.ImGenxB.imag_00_generate_s[6][7]} {PLxB.ImGenxB.imag_00_generate_s[6][8]} {PLxB.ImGenxB.imag_00_generate_s[6][9]} {PLxB.ImGenxB.imag_00_generate_s[6][10]} {PLxB.ImGenxB.imag_00_generate_s[6][11]} {PLxB.ImGenxB.imag_00_generate_s[6][12]} {PLxB.ImGenxB.imag_00_generate_s[6][13]} {PLxB.ImGenxB.imag_00_generate_s[6][14]} {PLxB.ImGenxB.imag_00_generate_s[6][15]} {PLxB.ImGenxB.imag_00_generate_s[6][16]} {PLxB.ImGenxB.imag_00_generate_s[6][17]}]]
set_property src_info {type:XDC file:2 line:107 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {PLxB.ImGenxB.imag_00_generate_s[5][0]} {PLxB.ImGenxB.imag_00_generate_s[5][1]} {PLxB.ImGenxB.imag_00_generate_s[5][2]} {PLxB.ImGenxB.imag_00_generate_s[5][3]} {PLxB.ImGenxB.imag_00_generate_s[5][4]} {PLxB.ImGenxB.imag_00_generate_s[5][5]} {PLxB.ImGenxB.imag_00_generate_s[5][6]} {PLxB.ImGenxB.imag_00_generate_s[5][7]} {PLxB.ImGenxB.imag_00_generate_s[5][8]} {PLxB.ImGenxB.imag_00_generate_s[5][9]} {PLxB.ImGenxB.imag_00_generate_s[5][10]} {PLxB.ImGenxB.imag_00_generate_s[5][11]} {PLxB.ImGenxB.imag_00_generate_s[5][12]} {PLxB.ImGenxB.imag_00_generate_s[5][13]} {PLxB.ImGenxB.imag_00_generate_s[5][14]} {PLxB.ImGenxB.imag_00_generate_s[5][15]} {PLxB.ImGenxB.imag_00_generate_s[5][16]} {PLxB.ImGenxB.imag_00_generate_s[5][17]}]]
set_property src_info {type:XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {PLxB.ImGenxB.imag_00_generate_s[7][0]} {PLxB.ImGenxB.imag_00_generate_s[7][1]} {PLxB.ImGenxB.imag_00_generate_s[7][2]} {PLxB.ImGenxB.imag_00_generate_s[7][3]} {PLxB.ImGenxB.imag_00_generate_s[7][4]} {PLxB.ImGenxB.imag_00_generate_s[7][5]} {PLxB.ImGenxB.imag_00_generate_s[7][6]} {PLxB.ImGenxB.imag_00_generate_s[7][7]} {PLxB.ImGenxB.imag_00_generate_s[7][8]} {PLxB.ImGenxB.imag_00_generate_s[7][9]} {PLxB.ImGenxB.imag_00_generate_s[7][10]} {PLxB.ImGenxB.imag_00_generate_s[7][11]} {PLxB.ImGenxB.imag_00_generate_s[7][12]} {PLxB.ImGenxB.imag_00_generate_s[7][13]} {PLxB.ImGenxB.imag_00_generate_s[7][14]} {PLxB.ImGenxB.imag_00_generate_s[7][15]} {PLxB.ImGenxB.imag_00_generate_s[7][16]} {PLxB.ImGenxB.imag_00_generate_s[7][17]}]]
set_property src_info {type:XDC file:2 line:110 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {PLxB.ImGenxB.imag_00_generate_s[2][0]} {PLxB.ImGenxB.imag_00_generate_s[2][1]} {PLxB.ImGenxB.imag_00_generate_s[2][2]} {PLxB.ImGenxB.imag_00_generate_s[2][3]} {PLxB.ImGenxB.imag_00_generate_s[2][4]} {PLxB.ImGenxB.imag_00_generate_s[2][5]} {PLxB.ImGenxB.imag_00_generate_s[2][6]} {PLxB.ImGenxB.imag_00_generate_s[2][7]} {PLxB.ImGenxB.imag_00_generate_s[2][8]} {PLxB.ImGenxB.imag_00_generate_s[2][9]} {PLxB.ImGenxB.imag_00_generate_s[2][10]} {PLxB.ImGenxB.imag_00_generate_s[2][11]} {PLxB.ImGenxB.imag_00_generate_s[2][12]} {PLxB.ImGenxB.imag_00_generate_s[2][13]} {PLxB.ImGenxB.imag_00_generate_s[2][14]} {PLxB.ImGenxB.imag_00_generate_s[2][15]} {PLxB.ImGenxB.imag_00_generate_s[2][16]} {PLxB.ImGenxB.imag_00_generate_s[2][17]}]]
set_property src_info {type:XDC file:2 line:111 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {PLxB.ImGenxB.imag_00_generate_s[3][0]} {PLxB.ImGenxB.imag_00_generate_s[3][1]} {PLxB.ImGenxB.imag_00_generate_s[3][2]} {PLxB.ImGenxB.imag_00_generate_s[3][3]} {PLxB.ImGenxB.imag_00_generate_s[3][4]} {PLxB.ImGenxB.imag_00_generate_s[3][5]} {PLxB.ImGenxB.imag_00_generate_s[3][6]} {PLxB.ImGenxB.imag_00_generate_s[3][7]} {PLxB.ImGenxB.imag_00_generate_s[3][8]} {PLxB.ImGenxB.imag_00_generate_s[3][9]} {PLxB.ImGenxB.imag_00_generate_s[3][10]} {PLxB.ImGenxB.imag_00_generate_s[3][11]} {PLxB.ImGenxB.imag_00_generate_s[3][12]} {PLxB.ImGenxB.imag_00_generate_s[3][13]} {PLxB.ImGenxB.imag_00_generate_s[3][14]} {PLxB.ImGenxB.imag_00_generate_s[3][15]} {PLxB.ImGenxB.imag_00_generate_s[3][16]} {PLxB.ImGenxB.imag_00_generate_s[3][17]}]]
set_property src_info {type:XDC file:2 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:116 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets Clk125xC]
