# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/mandelbrot/scalp_user_design/scalp_user_design.srcs/sources_1/ip/pll_mandel_1/pll_mandel.xci
# IP: The module: 'pll_mandel' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/mandelbrot/scalp_user_design/scalp_user_design.gen/sources_1/ip/pll_mandel_1/pll_mandel_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_mandel'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/mandelbrot/scalp_user_design/scalp_user_design.gen/sources_1/ip/pll_mandel_1/pll_mandel.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_mandel'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/mandelbrot/scalp_user_design/scalp_user_design.gen/sources_1/ip/pll_mandel_1/pll_mandel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_mandel'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/mandelbrot/scalp_user_design/scalp_user_design.srcs/sources_1/ip/pll_mandel_1/pll_mandel.xci
# IP: The module: 'pll_mandel' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/mandelbrot/scalp_user_design/scalp_user_design.gen/sources_1/ip/pll_mandel_1/pll_mandel_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_mandel'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/mandelbrot/scalp_user_design/scalp_user_design.gen/sources_1/ip/pll_mandel_1/pll_mandel.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_mandel'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/mandelbrot/scalp_user_design/scalp_user_design.gen/sources_1/ip/pll_mandel_1/pll_mandel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_mandel'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
