# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/mandelbrot/scalp_user_design/scalp_user_design.srcs/sources_1/bd/vga_hdmi_clk_rst_system/ip/vga_hdmi_clk_rst_system_vga_hdmi_clock_0/vga_hdmi_clk_rst_system_vga_hdmi_clock_0.xci
# IP: The module: 'vga_hdmi_clk_rst_system_vga_hdmi_clock_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/mandelbrot/scalp_user_design/scalp_user_design.gen/sources_1/bd/vga_hdmi_clk_rst_system/ip/vga_hdmi_clk_rst_system_vga_hdmi_clock_0/vga_hdmi_clk_rst_system_vga_hdmi_clock_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_hdmi_clk_rst_system_vga_hdmi_clock_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/mandelbrot/scalp_user_design/scalp_user_design.gen/sources_1/bd/vga_hdmi_clk_rst_system/ip/vga_hdmi_clk_rst_system_vga_hdmi_clock_0/vga_hdmi_clk_rst_system_vga_hdmi_clock_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_hdmi_clk_rst_system_vga_hdmi_clock_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/mandelbrot/scalp_user_design/scalp_user_design.gen/sources_1/bd/vga_hdmi_clk_rst_system/ip/vga_hdmi_clk_rst_system_vga_hdmi_clock_0/vga_hdmi_clk_rst_system_vga_hdmi_clock_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_hdmi_clk_rst_system_vga_hdmi_clock_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/mandelbrot/scalp_user_design/scalp_user_design.srcs/sources_1/bd/vga_hdmi_clk_rst_system/ip/vga_hdmi_clk_rst_system_vga_hdmi_clock_0/vga_hdmi_clk_rst_system_vga_hdmi_clock_0.xci
# IP: The module: 'vga_hdmi_clk_rst_system_vga_hdmi_clock_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/mandelbrot/scalp_user_design/scalp_user_design.gen/sources_1/bd/vga_hdmi_clk_rst_system/ip/vga_hdmi_clk_rst_system_vga_hdmi_clock_0/vga_hdmi_clk_rst_system_vga_hdmi_clock_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_hdmi_clk_rst_system_vga_hdmi_clock_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/mandelbrot/scalp_user_design/scalp_user_design.gen/sources_1/bd/vga_hdmi_clk_rst_system/ip/vga_hdmi_clk_rst_system_vga_hdmi_clock_0/vga_hdmi_clk_rst_system_vga_hdmi_clock_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_hdmi_clk_rst_system_vga_hdmi_clock_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/mandelbrot/scalp_user_design/scalp_user_design.gen/sources_1/bd/vga_hdmi_clk_rst_system/ip/vga_hdmi_clk_rst_system_vga_hdmi_clock_0/vga_hdmi_clk_rst_system_vga_hdmi_clock_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_hdmi_clk_rst_system_vga_hdmi_clock_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
