# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/scalp_revc_windows/scalp_zynqps/ip/scalp_zynqps_clk_wiz_0_0/scalp_zynqps_clk_wiz_0_0.xci
# IP: The module: 'scalp_zynqps_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/scalp_revc_windows/scalp_zynqps/ip/scalp_zynqps_clk_wiz_0_0/scalp_zynqps_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'scalp_zynqps_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/scalp_revc_windows/scalp_zynqps/ip/scalp_zynqps_clk_wiz_0_0/scalp_zynqps_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'scalp_zynqps_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/scalp_revc_windows/scalp_zynqps/ip/scalp_zynqps_clk_wiz_0_0/scalp_zynqps_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'scalp_zynqps_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/scalp_revc_windows/scalp_zynqps/ip/scalp_zynqps_clk_wiz_0_0/scalp_zynqps_clk_wiz_0_0.xci
# IP: The module: 'scalp_zynqps_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/scalp_revc_windows/scalp_zynqps/ip/scalp_zynqps_clk_wiz_0_0/scalp_zynqps_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'scalp_zynqps_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/scalp_revc_windows/scalp_zynqps/ip/scalp_zynqps_clk_wiz_0_0/scalp_zynqps_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'scalp_zynqps_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/scalp_revc_windows/scalp_zynqps/ip/scalp_zynqps_clk_wiz_0_0/scalp_zynqps_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'scalp_zynqps_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
